#include "PC131415.h"

void C131415_Init(void) {
		RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN;

		GPIOC->MODER &= ~GPIO_MODER_MODE13;
		GPIOC->MODER |= GPIO_MODER_MODE13_0;

		GPIOC->MODER &= ~GPIO_MODER_MODE14;
		GPIOC->MODER |= GPIO_MODER_MODE14_0;

		GPIOC->MODER &= ~GPIO_MODER_MODE15;
		GPIOC->MODER |= GPIO_MODER_MODE15_0;
}

void WritePinsC131415(uint8_t value)
{
    GPIOC->BSRR = GPIO_BSRR_BR13 | GPIO_BSRR_BR14 | GPIO_BSRR_BR15;
    
    if (value & 1) GPIOC->BSRR = GPIO_BSRR_BS13;
    
    if (value & 2) GPIOC->BSRR = GPIO_BSRR_BS14;
    
    if (value & 4) GPIOC->BSRR = GPIO_BSRR_BS15;
}
