#include "PB12131415.h"

void B12131415_Init(void) {
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOBEN;
		GPIOB->MODER &= ~GPIO_MODER_MODE12;
		GPIOB->MODER |= GPIO_MODER_MODE12_0; 
	
		//GPIOB->BSRR = GPIO_BSRR_BS4;
		//GPIOB->BSRR = GPIO_BSRR_BR4;
		GPIOB->MODER &= ~GPIO_MODER_MODE13;
		GPIOB->MODER |= GPIO_MODER_MODE13_0; 
	
		GPIOB->MODER &= ~GPIO_MODER_MODE14;
		GPIOB->MODER |= GPIO_MODER_MODE14_0;
	
		GPIOB->MODER &= ~GPIO_MODER_MODE15;
		GPIOB->MODER |= GPIO_MODER_MODE15_0; 
	
		GPIOB->BSRR |= GPIO_BSRR_BS12;
		GPIOB->BSRR |= GPIO_BSRR_BS13;
		GPIOB->BSRR |= GPIO_BSRR_BS14;
		GPIOB->BSRR |= GPIO_BSRR_BS15;
}
